snscrape script
TechBlurbs/maandamano-mondays-sentiment-analysis pull request #13
Opened 2023-03-31 22:27 UTC by ashioyajotham

2023-04-02 09:29 UTC, VictorOmondi1997 requested changes

2023-04-02 09:29 UTC, VictorOmondi1997 commented on data_collection/sns_scrape.py
> +# We are going to scrape Twitter using snscrape
To make sure the lint is passing, the python file line 1 needs to be a docstring to explain what the .py file is about.
```suggestion
"""We are going to scrape Twitter using snscrape"""
```

2023-04-02 09:29 UTC, VictorOmondi1997 commented on data_collection/sns_scrape.py
Thank you @ashioyajotham for exploring snscrape library. This looks great, but there are some few things that needs to be addressed before we merge it to main:
![image](https://user-images.githubusercontent.com/33686520/229344005-914d210e-1620-48da-bbcb-fc2f381fb33d.png)

When experiencing this 👇🏿  just make sure the library is part of our `requirements.txt`
```
data_collection/sns_scrape.py:3:0: E0401: Unable to import 'pandas' (import-error)
data_collection/sns_scrape.py:4:0: E0401: Unable to import 'numpy' (import-error)
```

2023-04-02 09:29 UTC, VictorOmondi1997 commented on data_collection/sns_scrape.py
> +import datetime
There are some libraries that you've imported that have not been used in this script, those are `numpy` and `csv`. Our lint tool will show you some of this.
```suggestion
import pandas as pd
import snscrape.modules.twitter as sntwitter
import datetime
```

2023-04-03 03:14 UTC, 3liud approved these changes

2023-04-03 05:20 UTC, Stephen-Kamau approved these changes
good

2023-04-03 07:22 UTC, merged